sensor:
  - platform: pulse_counter
    unit_of_measurement: 'Gallons per Minute'
    name: "Zone 9"
    filters:
      - multiply: 10
    pin:
        number: GPIO36
        inverted: true
        drive_strength: 10.0

    update_interval : 60s

    total:
      unit_of_measurement: 'Gallons'
      name: 'Zone 9 Total Gallons'
      filters:
        - multiply: 10 
