sensor:
  - platform: pulse_counter
    unit_of_measurement: 'Gallons'
    name: "Zone 2"
    filters:
      - multiply: 1 
    pin: GPIO02
    update_interval : 60s

    total:
      unit_of_measurement: 'Gallons'
      name: 'Zone 2 Total Gallons'
      filters:
        - multiply: 10
