sensor:
  - platform: pulse_meter
    name: 'Zone 1'
    id: zone_1_pulse_meter
    unit_of_measurement: 'L'
    device_class: water
    state_class: measurement   
    internal_filter_mode: pulse
    internal_filter: 200ms 
    timeout: 1m
    accuracy_decimals: 0
    pin:
        number: GPIO04
        inverted: true
        mode:
          input: true
          pullup: true
   
    filters:
      - multiply: 1
      - heartbeat: 1s
      
    total:
      name: "Zone 1 Total Pulses"
