sensor:
  - platform: pulse_counter
    unit_of_measurement: 'Gallons'
    name: "Zone 3"
    filters:
      - multiply: 6  # (60s/0.1 pulse per Gallon)
    pin: GPIO15
    update_interval : 60s

    total:
      unit_of_measurement: 'Gallons'
      name: 'Zone 3 Total Gallons'
      filters:
        - multiply: 10  # (1/10 pulses per 10 Gallons)
