sensor:
  - platform: pulse_counter
    unit_of_measurement: 'Litters per Minute'
    name: "Zone 1"
    filters:
      - multiply: 1
    pin: GPIO04
    update_interval : 60s

    total:
      unit_of_measurement: 'Liters'
      name: 'Zone 1 Total Liters'
      filters:
        - multiply: 1 
