sensor:
  - platform: pulse_width
    name: 'Zone 7'
    id: zone_7_pulse_meter
    update_interval: 1s    
    pin:
        number: GPIO33
        inverted: true
        drive_strength: 10.0
        mode:
          input: true
          pullup: true
