sensor:
  - platform: pulse_counter
    unit_of_measurement: 'Gallons per Minute
    name: "Zone 7"
    filters:
      - multiply: 10
    pin: GPIO33
    update_interval : 60s

    total:
      unit_of_measurement: 'Gallons'
      name: 'Zone 7 Total Gallons'
      filters:
        - multiply: 10 
