sensor:
  - platform: pulse_width
    name: 'Zone 1.2'
    id: zone_1_2_pulse_meter
    update_interval: 1s    
    pin:
        number: GPIO04
        inverted: true
        mode:
          input: true
          pullup: true

 total:
      name: "Zone 1.2 Total Pulses"
