sensor:
  - platform: pulse_meter
    name: 'Zone 1'
    id: zone_1_pulse_meter_2
    pin:
        number: GPIO04
        inverted: true
        drive_strength: 10.0
        mode:
          input: true
          pullup: true
