sensor:
  - platform: pulse_counter
    unit_of_measurement: 'Gallons'
    name: "Zone 1"
    filters:
      - multiply: 10  # (60s/10 pulse per Gallon)
    pin: GPIO04
    update_interval : 60s

    total:
      unit_of_measurement: 'Gallons'
      name: 'Zone 1 Total Gallons'
      filters:
        - multiply: 10  # (1/10 pulses per 10 Gallons)
