sensor:
  - platform: pulse_counter
    unit_of_measurement: 'Liters per Minute'
    name: "Zone 7"
    filters:
      - multiply: 1
    pin:
        number: GPIO33
        inverted: true
        mode:
          input: true
          pullup: true
    update_interval : 60s

    total:
      unit_of_measurement: 'Liters'
      name: 'Zone 7 Total Liters'
      filters:
        - multiply: 1 
