sensor:
  - platform: pulse_counter
    unit_of_measurement: 'Gallons per Minute'
    name: "Zone 5"
    filters:
      - multiply: 10
    pin: GPIO18
    update_interval : 60s

    total:
      unit_of_measurement: 'Gallons'
      name: 'Zone 5 Total Gallons'
      filters:
        - multiply: 10 
