sensor:
  - platform: pulse_counter
    unit_of_measurement: 'Gallons per Hour'
    name: "Zone 3"
    filters:
      - multiply: 10
    pin: GPIO15
    update_interval : 60s

    total:
      unit_of_measurement: 'Gallons'
      name: 'Zone 3 Total Gallons'
      filters:
        - multiply: 10 
