sensor:
  - platform: pulse_counter
    unit_of_measurement: 'Gallons per Hour'
    name: "Zone 11"
    filters:
      - multiply: 10
    pin: GPIO34
    update_interval : 3600s

    total:
      unit_of_measurement: 'Gallons'
      name: 'Zone 11 Total Gallons'
      filters:
        - multiply: 10 
