sensor:
  - platform: pulse_counter
    unit_of_measurement: 'Litters per Minute'
    name: "Zone 7"
    filters:
      - multiply: 1
    pin: GPIO33
    update_interval : 60s

    total:
      unit_of_measurement: 'Liters'
      name: 'Zone 7 Total Liters'
      filters:
        - multiply: 1 
