sensor:
  - platform: pulse_width
    name: 'Zone 5'
    id: zone_5_pulse_meter
    update_interval: 1s    
    pin:
        number: GPIO13
        inverted: true
        drive_strength: 10.0
        mode:
          input: true
          pullup: true
