sensor:
  - platform: pulse_counter
    unit_of_measurement: 'Liters per Minute'
    name: "Zone 5"
    filters:
      - multiply: 1
    pin:
        number: GPIO18
        inverted: true
        drive_strength: 10.0
        mode:
          input: true
          pullup: true
    update_interval : 60s

    total:
      unit_of_measurement: 'Liters'
      name: 'Zone 5 Total Liters'
      filters:
        - multiply: 1
