sensor:
  - platform: pulse_counter
    unit_of_measurement: 'Litters per Minute'
    name: "Zone 1"
    filters:
      - multiply: 1
    pin:
        number: GPIO04
        inverted: true
        mode:
          input: true
          pullup: true
    update_interval : 60s

    total:
      unit_of_measurement: 'Liters'
      name: 'Zone 1 Total Liters'
      filters:
        - multiply: 1 
