sensor:
  - platform: pulse_counter
    unit_of_measurement: 'Gallons'
    name: "Zone 3"
    filters:
      - multiply: 1 
    pin: GPIO15
    inverted: false
    mode:
      input: true
      pullup: true
    update_interval : 60s

    total:
      unit_of_measurement: 'Gallons'
      name: 'Zone 3 Total Gallons'
      filters:
        - multiply: 10 
