sensor:
  - platform: pulse_width
    name: 'Zone 1.2'
    id: zone_1_2_pulse_meter
    update_interval: 1s    
    pin:
        number: GPIO04
        inverted: true
        drive_strength: 10.0
        mode:
          input: true
          pullup: true
