sensor:
  - platform: pulse_counter
    unit_of_measurement: 'Gallons per Minute'
    name: "Zone 11"
    filters:
      - multiply: 10
    pin: GPIO34
        drive_strength: 10.0
    update_interval : 60s

    total:
      unit_of_measurement: 'Gallons'
      name: 'Zone 11 Total Gallons'
      filters:
        - multiply: 10 
