sensor:
  - platform: pulse_counter
    unit_of_measurement: 'Gallons'
    name: "Zone 4"
    filters:
      - multiply: 1  # (60s/0.1 pulse per Gallon)
    pin: GPIO13
    update_interval : 60s

    total:
      unit_of_measurement: 'Gallons'
      name: 'Zone 4 Total Gallons'
      filters:
        - multiply: 10  # (1 pulses per 10 Gallons)
