sensor:
  - platform: pulse_meter
    name: 'Zone 3'
    id: zone_3_pulse_meter_1
    update_interval: 1s    
    pin:
        number: GPIO15
        inverted: true
        drive_strength: 10.0
        mode:
          input: true
          pullup: true
