esphome:
  name: $name
  friendly_name: $friendly_name
  name_add_mac_suffix: true
  project:
    name: $project_name
    version: $project_version
  platformio_options:
    board_build.flash_mode: dio
  on_boot:
    priority: 800.0
    then:
      - text_sensor.template.publish:
          id: device_id
          state: !lambda 'return get_mac_address();'

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf
    version: recommended
    sdkconfig_options:
      CONFIG_LWIP_MAX_SOCKETS: "16"
      CONFIG_ESP_SYSTEM_PANIC_SILENT_REBOOT: y
      CONFIG_ESP_SYSTEM_PANIC_PRINT_REBOOT: n

substitutions:
  status_led_inverted: "false"

# overrides the MDNS component to add a Konnected service
external_components:
  - source: github://konnected-io/konnected-esphome@master
    components: [ mdns, secplus_gdo ]

text_sensor:
  - platform: template
    name: Device ID
    id: device_id
    entity_category: diagnostic
    update_interval: never
  - platform: version
    name: ESPHome Version
    hide_timestamp: true

sensor:
  - platform: uptime
    name: Uptime
    id: uptime_sensor
    entity_category: diagnostic

button:
  - platform: restart
    name: Restart
    id: restart_button
    entity_category: config

#### 
# OTA UPDATES
# Enables over-the-air updates
# more: https://esphome.io/components/ota.html
ota:
  - platform: esphome
    id: konnected_ota

